# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20180609_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('group_id', models.CharField(help_text='user id', max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'selecionado'), (2, 'cerrado')], default=1)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Conversation')),
            ],
            options={
                'ordering': ['-created'],
                'default_permissions': ('add', 'change', 'delete', 'get', 'list', 'patch'),
            },
        ),
    ]
